export const logInConstant = {
    EDIT_EMAIL_LOGIN: 'EDIT_EMAIL_LOGIN',
    EDIT_PASS_LOGIN: 'EDIT_PASS_LOGIN',
    LOGGING_IN: 'LOGGING_IN',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    CHECK_TENANT_EXIST: 'CHECK_TENANT_EXIST',
    CHECK_TENANT_EXIST_SUCCESS: 'CHECK_TENANT_EXIST_SUCCESS',
    CHECK_TENANT_EXIST_FAILURE: 'CHECK_TENANT_EXIST_FAILURE',
    GETTING_VERIFY_USER: 'GETTING_VERIFY_USER' ,
    GET_VERIFY_USER_SUCCESS: 'GETTING_VERIFY_USER_SUCCESS' ,
    GET_VERIFY_USER_ERROR: 'GETTING_VERIFY_USER_ERROR' ,
    UPDATE_LOGIN_CRED: 'UPDATE_LOGIN_CRED'
}

export const signUpConstant = {
    SIGNUP_EDIT:'SIGNUP_EDIT',
    SIGNING_UP: 'SIGNING_UP',
    SIGNUP_SUCCESS:'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE'
}

export const inviteConstant = {
    LIST_INVITES: 'LIST_INVITES',
    ADD_INVITE: 'ADD_INVITE',
    EDIT_INVITE: 'EDIT_INVITE',
    DELETE_INVITE: 'DELETE_INVITE',
    SENDING_INVITE: 'SENDING_INVITE',
    SEND_INVITE_SUCCESS: 'SEND_INVITE_SUCCESS',
    SEND_INVITE_ERROR: 'SEND_INVITE_ERROR',
    RESET_INVITE: 'RESET_INVITE' 
}

// Onboarding screen profile
export const profileConstant = {
    GETTING_PROFILE: 'GETTING_PROFILE',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_ERROR: 'GET_PROFILE_ERROR',
    EDIT_PROFILE: 'EDIT_PROFILE',
    SAVE_PROFILE: 'SAVE_PROFILE',
    SAVE_PROFILE_SUCCESS: 'SAVE_PROFILE_SUCCESS',
    SAVE_PROFILE_ERROR: 'SAVE_PROFILE_ERROR',
    RESET_PROFILE: 'RESET_PROFILE' 
}

export const skillsConstant = {
    GET_SKILLS: 'GET_SKILLS',
    GET_SKILLS_SUCCESS: 'GET_SKILLS_SUCCESS',
    GET_SKILLS_ERROR: 'GET_SKILLS_ERROR',
    GET_USER_SKILLS: 'GET_USER_SKILLS',
    GET_USER_SKILLS_SUCCESS: 'GET_USER_SKILLS_SUCCESS',
    GET_USER_SKILLS_ERROR: 'GET_USER_SKILLS_ERROR',
    EDIT_USER_SKILLS: 'EDIT_USER_SKILLS',
    SAVING_USER_SKILLS: 'SAVING_USER_SKILLS',
    SAVE_USER_SKILLS_SUCCESS: 'SAVE_USER_SKILLS_SUCCESS',
    SAVE_USER_SKILLS_FAILED: 'SAVE_USER_SKILLS_FAILED'
}

export const userConstant = {
    GETTING_USER: 'GETTING_USER',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_ERROR: 'GET_USER_ERROR',
    EDIT_USER: 'EDIT_USER',
    SET_EDIT_MODE: 'SET_EDIT_MODE',
    SAVING_USER: 'SAVING_USER',
    SAVE_USER_SUCCESS: 'SAVE_USER_SUCCESS',
    SAVE_USER_ERROR: 'SAVE_USER_ERROR',
    RESET_USER: 'RESET_USER',
    LOADING: 'LOADING' 
}

export const adminConstant = {
    UPLOADING : 'UPLOADING',
    UPLOAD_SUCCESS : 'UPLOAD_SUCCESS',
    UPLOAD_ERROR : 'UPLOAD_ERROR',
    GET_CSV: 'GET_CSV'
}

export const weeklyUpdatesConstants = {
    WEEK_CHANGE: 'WEEK_CHANGE',
    EDIT_EXECUTION: 'EDIT_EXECUTION',
    EDIT_CRAFTSMANSHIP: 'EDIT_CRAFTSMANSHIP',
    EDIT_LEADERSHIP: 'EDIT_LEADERSHIP',
    EDIT_MENTORING: 'EDIT_MENTORING',
    EDITING_WEEKLY_UPDATE: 'EDITING_WEEKLY_UPDATE',
    EDIT_WEEKLY_UPDATE: 'EDIT_WEEKLY_UPDATE',
    CANCEL_EDITING_WEEKLY_UPDATE: 'CANCEL_EDITING_WEEKLY_UPDATE',
    SAVING_WEEKLY_UPDATE: 'SAVING_WEEKLY_UPDATE',
    SAVE_WEEKLY_UPDATE_SUCCESS: 'SAVE_WEEKLY_UPDATE_SUCCESS',
    SAVE_WEEKLY_UPDATE_ERROR: 'SAVE_WEEKLY_UPDATE_ERROR',
    SELECTED_DAYS: 'SELECTED_DAYS'
}

export const workHighlightsConstants = {
    EDIT_WORK_HIGHLIGHTS: 'EDIT_WORK_HIGHLIGHTS',
    EDITING_WORK_HIGHLIGHTS: 'EDITING_WORK_HIGHLIGHTS',
    CANCEL_EDITING_WORK_HIGHLIGHTS: 'CANCEL_EDITING_WORK_HIGHLIGHTS',
    EDIT_WORK_HIGHLIGHTS_SUCCESS: 'EDIT_WORK_HIGHLIGHTS_SUCCESS',
    EDIT_WORK_HIGHLIGHTS_ERROR: 'EDIT_WORK_HIGHLIGHTS_ERROR'
}

export const myCoursesConstants = {
    LIST_ACHIEVEMENTS: 'LIST_ACHIEVEMENTS',
    
    GETTING_COURSES: 'GETTING_COURSES',
    GET_COURSES_SUCCESS: 'GET_COURSES_SUCCESS',
    GET_COURSES_ERROR: 'GET_COURSES_ERROR',

    ADDING_COURSE: 'ADDING_COURSE',
    ADD_COURSE_SUCCESS: 'ADD_COURSE_SUCCESS',
    ADD_COURSE_ERROR: 'ADD_COURSE_ERROR',

    UPDATING_COURSE: 'UPDATING_COURSE',
    UPDATE_COURSE_SUCCESS: 'UPDATE_COURSE_SUCCESS',
    UPDATE_COURSE_ERROR: 'UPDATE_COURSE_ERROR',

    DELETING_COURSE: 'DELETING_COURSE',
    DELETE_COURSE_SUCCESS: 'DELETE_COURSE_SUCCESS',
    DELETE_COURSE_ERROR: 'DELETE_COURSE_ERROR',
    
    EDIT_COURSE: 'EDIT_COURSE',
    EDIT_NEW_COURSE: 'EDIT_NEW_COURSE',
    RESET_COURSE: 'RESET_COURSE',

    UNFURLING: 'UNFURLING',
    UNFURLING_SUCCESS: 'UNFURLING_SUCCESS',
    UNFURLING_ERROR: 'UNFURLING_ERROR',

    SENDING_RECOMMED: 'SENDING_RECOMMED',
    SEND_RECOMMED_SUCCESS: 'SEND_RECOMMED_SUCCESS',
    SEND_RECOMMED_ERROR: 'SEND_RECOMMED_ERROR',
    RESET_RECOMMED: 'RESET_RECOMMED',

    GETTING_USER_RECOMMEND: 'GETTING_USER_RECOMMEND',
    GET_USER_RECOMMEND_SUCCESS: 'GET_USER_RECOMMEND_SUCCESS',
    GET_USER_RECOMMEND_ERROR: 'GET_USER_RECOMMEND_ERROR',

}

export const careerLadderConstants = {
   EDIT_LADDER: 'EDIT_LADDER',
   ADD_LADDER: 'ADD_LADDER',
   DELETE_LADDER: 'DELETE_LADDER'
}

export const recommendCoursesConstants = {
    FETCH_COURSES_START: 'FETCH_COURSES_START',
    FETCH_COURSES_SUCCESS: 'FETCH_COURSES_SUCCESS',
    FETCH_COURSES_FAIL: 'FETCH_COURSES_FAIL'
}

export const customCoursesConstants = {
    UPDATE_STEP: 'UPDATE_STEP',
    UPDATE_STEP_IFRAME_URL: 'UPDATE_STEP_IFRAME_URL',
    ADD_STEP: 'ADD_STEP',
    DELETE_STEP: 'DELETE_STEP',
    EDIT_STEP: 'EDIT_STEP',
    UPDATE_COURSE: 'UPDATE_COURSE',
    RESET_CUSTOM_COURSE: 'RESET_CUSTOM_COURSE',

    SAVING_COURSE: 'SAVING_COURSE',
    SAVE_COURSE_SUCCESS: 'SAVE_COURSE_SUCCESS',
    SAVE_COURSE_FAIL: 'SAVE_COURSE_FAIL',

    GETTING_CUSTOM_COURSES: 'GETTING_CUSTOM_COURSES',
    GET_CUSTOM_COURSES_SUCCESS: 'GET_CUSTOM_COURSES_SUCCESS',
    GET_CUSTOM_COURSES_FAIL: 'GET_CUSTOM_COURSES_FAIL',

    GETTING_CUSTOM_COURSE: 'GETTING_CUSTOM_COURSE',
    GET_CUSTOM_COURSE_SUCCESS: 'GET_CUSTOM_COURSE_SUCCESS',
    GET_CUSTOM_COURSE_FAIL: 'GET_CUSTOM_COURSE_FAIL',

    DELETING_CUSTOM_COURSE: 'DELETING_CUSTOM_COURSE',
    DELETE_CUSTOM_COURSE_SUCCESS: 'DELETE_CUSTOM_COURSE_SUCCESS',
    DELETE_CUSTOM_COURSE_FAIL: 'DELETE_CUSTOM_COURSE_FAIL',

    DELETING_DRAFT_CUSTOM_COURSE: 'DELETING_DRAFT_CUSTOM_COURSE',
    DELETE_DRAFT_CUSTOM_COURSE_SUCCESS: 'DELETE_DRAFT_CUSTOM_COURSE_SUCCESS',
    DELETE_DRAFT_CUSTOM_COURSE_FAIL: 'DELETE_DRAFT_CUSTOM_COURSE_FAIL',

    GETTING_CUSTOM_COURSES_LIBRARY: 'GETTING_CUSTOM_COURSES_LIBRARY',
    GET_CUSTOM_COURSES_LIBRARY_SUCCESS: 'GET_CUSTOM_COURSES_LIBRARY_SUCCESS',
    GET_CUSTOM_COURSES_LIBRARY_FAIL: 'GET_CUSTOM_COURSES_LIBRARY_FAIL',

    UPLOADING_STEP_PITCH: 'UPLOADING_STEP_PITCH',
    UPLOAD_STEP_PITCH_SUCCESS: 'UPLOAD_STEP_PITCH_SUCCESS',
    UPLOAD_STEP_PITCH_FAIL: 'UPLOAD_STEP_PITCH_FAIL',

    ADDING_STEP_INFO: 'ADDING_STEP_INFO',
    ADD_STEP_INFO_SUCCESS: 'ADD_STEP_INFO_SUCCESS',
    ADD_STEP_INFO_FAIL: 'ADD_STEP_INFO_FAIL',
}

export const assignConstant = {
    ADD_ASSIGNEE: 'ADD_ASSIGNEE',
    EDIT_ASSIGNEE: 'EDIT_ASSIGNEE',
    DELETE_ASSIGNEE: 'DELETE_ASSIGNEE',
 
    SENDING_ASSIGNEE: 'SENDING_ASSIGNEE',
    SEND_ASSIGNEE_SUCCESS: 'SEND_ASSIGNEE_SUCCESS',
    SEND_ASSIGNEE_ERROR: 'SEND_ASSIGNEE_ERROR',
    RESET_ASSIGNEE: 'RESET_ASSIGNEE',

    SENDING_TEAM_ASSIGNEE: 'SENDING_TEAM_ASSIGNEE',
    SEND_TEAM_ASSIGNEE_SUCCESS: 'SEND_TEAM_ASSIGNEE_SUCCESS',
    SEND_TEAM_ASSIGNEE_ERROR: 'SEND_TEAM_ASSIGNEE_ERROR',

    GETTING_CUSTOM_ASSIGN_COURSES: 'GETTING_CUSTOM_ASSIGN_COURSES',
    GET_CUSTOM_ASSIGN_COURSES_SUCCESS: 'GET_CUSTOM_ASSIGN_COURSES_SUCCESS',
    GET_CUSTOM_ASSIGN_COURSES_FAIL: 'GET_CUSTOM_ASSIGN_COURSES_FAIL',

    STARTING_COURSE: 'STARTING_COURSE',
    START_COURSE_SUCCESS: 'START_COURSE_SUCCESS',
    START_COURSE_FAIL: 'START_COURSE_FAIL',

    MARKING_COURSE_STEP: 'MARKING_COURSE_STEP',
    MARK_COURSE_STEP_SUCCESS: 'MARK_COURSE_STEP_SUCCESS',
    MARK_COURSE_STEP_FAIL:  'MARK_COURSE_STEP_FAIL',

    COMPELETING_CUSTOM_COURSE: 'COMPELETING_CUSTOM_COURSE',
    COMPELETE_CUSTOM_COURSE_SUCCESS: 'COMPELETE_CUSTOM_COURSE_SUCCESS',
    COMPELETE_CUSTOM_COURSE_FAIL:  'COMPELETE_CUSTOM_COURSE_FAIL',
}

export const samlSettingConstants = {
    GETTING_SAML_SETTINGS: 'GETTING_SAML_SETTINGS',
    GET_SAML_SETTINGS_SUCCESS: 'GET_SAML_SETTINGS_SUCCESS',
    GET_SAML_SETTINGS_FAIL: 'GET_SAML_SETTINGS_FAIL',

    SAVING_SAML_SETTINGS: 'SAVING_SAML_SETTINGS',
    SAVE_SAML_SETTINGS_SUCCESS: 'SAVE_SAML_SETTINGS_SUCCESS',
    SAVE_SAML_SETTINGS_FAIL: 'SAVE_SAML_SETTINGS_FAIL',

    SAVING_SAML_METADATA: 'SAVING_SAML_METADATA',
    SAVE_SAML_METADATA_SUCCESS: 'SAVE_SAML_METADATA_SUCCESS',
    SAVE_SAML_METADATA_FAIL: 'SAVE_SAML_METADATA_FAIL',

    SAVING_ADMIN_PASSWORD: 'SAVING_ADMIN_PASSWORD',
    SAVE_ADMIN_PASSWORD_SUCCESS: 'SAVE_ADMIN_PASSWORD_SUCCESS',
    SAVE_ADMIN_PASSWORD_FAIL: 'SAVE_ADMIN_PASSWORD_FAIL',
    EDIT_ADMIN_PASSWORD_STATE: 'EDIT_ADMIN_PASSWORD_STATE',
}

export const myAchievements = {
    ADD_ACHIVEMENTS_START: 'ADD_ACHIVEMENTS_START',
    ADD_ACHIVEMENTS_SUCCESS: 'ADD_ACHIVEMENTS_SUCCESS',
    ADD_ACHIVEMENTS_FAIL: 'ADD_ACHIVEMENTS_FAIL',

    GET_ACHIVEMENTS_START: 'GET_ACHIVEMENTS_START',
    GET_ACHIVEMENTS_SUCCESS: 'GET_ACHIVEMENTS_SUCCESS',
    GET_ACHIVEMENTS_FAIL: 'GET_ACHIVEMENTS_FAIL',
}

export const analyticsCourses = {
    GETTING_ANALYTICS_COURSES: 'GETTING_ANALYTICS_COURSES',
    GET_ANALYTICS_COURSES_SUCCESS: 'GET_ANALYTICS_COURSES_SUCCESS',
    GET_ANALYTICS_COURSES_FAIL: 'GET_ANALYTICS_COURSES_FAIL',

    GETTING_ANALYTICS_COURSE: 'GETTING_ANALYTICS_COURSE',
    GET_ANALYTICS_COURSE_SUCCESS: 'GET_ANALYTICS_COURSE_SUCCESS',
    GET_ANALYTICS_COURSE_FAIL: 'GET_ANALYTICS_COURSE_FAIL',
}

export const deleteLearningAnalyticsCourses = {
    DELETING_LEARNING_ANALYTICS_COURSES: 'DELETING_LEARNING_ANALYTICS_COURSES',
    DELETE_LEARNING_ANALYTICS_COURSES_SUCCESS: 'DELETE_LEARNING_ANALYTICS_COURSES_SUCCESS',
    DELETE_LEARNING_ANALYTICS_COURSES_FAIL: 'DELETE_LEARNING_ANALYTICS_COURSES_FAIL',
}

export const analyticsLearners = {
    GETTING_ANALYTICS_LEARNERS: 'GETTING_ANALYTICS_LEARNERS',
    GET_ANALYTICS_LEARNERS_SUCCESS: 'GET_ANALYTICS_LEARNERS_SUCCESS',
    GET_ANALYTICS_LEARNERS_FAIL: 'GET_ANALYTICS_LEARNERS_FAIL',

    GETTING_ANALYTICS_LEARNER: 'GETTING_ANALYTICS_LEARNER',
    GET_ANALYTICS_LEARNER_SUCCESS: 'GET_ANALYTICS_LEARNER_SUCCESS',
    GET_ANALYTICS_LEARNER_FAIL: 'GET_ANALYTICS_LEARNER_FAIL',
}

export const analyticsDirectReports = {
    GETTING_DIRECT_REPORTS: 'GETTING_DIRECT_REPORTS',
    GET_DIRECT_REPORTS_SUCCESS: 'GET_DIRECT_REPORTS_SUCCESS',
    GET_DIRECT_REPORTS_FAIL: 'GET_DIRECT_REPORTS_FAIL',
}

export const analyticsMyLearning = {
    GETTING_MY_LEARNING: 'GETTING_MY_LEARNING',
    GET_MY_LEARNING_SUCCESS: 'GET_MY_LEARNING_SUCCESS',
    GET_MY_LEARNING_FAIL: 'GET_MY_LEARNING_FAIL',

    GETTING_TOP_LEARNINGS: 'GETTING_TOP_LEARNINGS',
    GET_TOP_LEARNINGS_SUCCESS: 'GET_TOP_LEARNINGS_SUCCESS',
    GET_TOP_LEARNINGS_FAIL: 'GET_TOP_LEARNINGS_FAIL',
}

export const publicViewPage = {
    GETTING_PUBLIC_DATA: 'GETTING_PUBLIC_DATA',
    GETTING_PUBLIC_DATA_SUCCESS: 'GETTING_PUBLIC_DATA_SUCCESS',
    GETTING_PUBLIC_DATA_FAIL: 'GETTING_PUBLIC_DATA_FAIL'
}

export const searchApi = {
    SEARCH_REQUEST_START: 'SEARCH_REQUEST_START',
    SEARCH_REQUEST_SUCCESS: 'SEARCH_REQUEST_SUCCESS',
    SEARCH_REQUEST_FAIL: 'SEARCH_REQUEST_FAIL'
}

export const feedbackConstant = {
    GETTING_FEEDBACK_REQUESTED: 'GETTING_FEEDBACK_REQUESTED',
    GET_FEEDBACK_REQUESTED_SUCCESS: 'GET_FEEDBACK_REQUESTED_SUCCESS',
    GET_FEEDBACK_REQUESTED_FAIL: 'GET_FEEDBACK_REQUESTED_FAIL',

    GETTING_FEEDBACK_FOR_ME: 'GETTING_FEEDBACK_FOR_ME',
    GET_FEEDBACK_FOR_ME_SUCCESS: 'GET_FEEDBACK_FOR_ME_SUCCESS',
    GET_FEEDBACK_FOR_ME_FAIL: 'GET_FEEDBACK_FOR_ME_FAIL',

    SAVING_FEEDBACK: 'SAVING_FEEDBACK',
    SAVE_FEEDBACK_SUCESS: 'SAVE_FEEDBACK_SUCESS',
    SAVE_FEEDBACK_FAIL: 'SAVE_FEEDBACK_FAIL'
}

export const quizBuilderConstant = {
    OPEN_Q_BUILDER: 'OPEN_Q_BUILDER',
    CLOSE_Q_BUILDER: 'CLOSE_Q_BUILDER',
    TOGGLE_PREVIEW_MODE: 'TOGGLE_PREVIEW_MODE',
    GET_QUIZ: 'GET_QUIZ',
    SET_ACTIVE_QUES: 'SET_ACTIVE_QUES',
    EDIT_QUES: 'EDIT_QUES',
    ADD_QUES: 'ADD_QUES',
    ADD_WELCOME_TEXT: 'ADD_WELCOME_TEXT',
    EDIT_WELCOME_TEXT: 'EDIT_WELCOME_TEXT',
    DEL_WELCOME_TEXT: 'DEL_WELCOME_TEXT',
    DELETE_QUES: 'DELETE_QUES',
    ADD_QUES_OPTION: 'ADD_QUES_OPTION',
    EDIT_QUES_OPTION: 'EDIT_QUES_OPTION',
    DEL_QUES_OPTION: 'DEL_QUES_OPTION'
}

export const peopleAccessConstants = {
    GETTING_PEOPLE_ACCESS: 'GETTING_PEOPLE_ACCESS',
    GET_PEOPLE_ACCESS_SUCCESS: 'GET_PEOPLE_ACCESS_SUCCESS',
    GET_PEOPLE_ACCESS_FAIL: 'GET_PEOPLE_ACCESS_FAIL',
    UPDATING_PEOPLE_ACCESS: 'UPDATING_PEOPLE_ACCESS',
    UPDATE_PEOPLE_ACCESS_SUCCESS: 'UPDATE_PEOPLE_ACCESS_SUCCESS',
    UPDATE_PEOPLE_ACCESS_FAIL: 'UPDATE_PEOPLE_ACCESS_FAIL',
}

export const integrationsConstants = {
    SETTING_SALESFORCE_EMAIL: 'SETTING_SALESFORCE_EMAIL',
    SET_SALESFORCE_EMAIL_SUCCESS: 'SET_SALESFORCE_EMAIL',
    SET_SALESFORCE_EMAIL_FAIL: 'SET_SALESFORCE_EMAIL_FAIL',
    GETTING_SALESFORCE_EMAIL: 'GETTING_SALESFORCE_EMAIL',
    GET_SALESFORCE_EMAIL_SUCCESS: 'GET_SALESFORCE_EMAIL',
    GET_SALESFORCE_EMAIL_FAIL: 'GET_SALESFORCE_EMAIL_FAIL',
}

export const addTeamsConstant = {
    LIST_TEAMS: 'LIST_TEAMS',
    ADD_TEAM: 'ADD_TEAM',
    EDIT_TEAM: 'EDIT_TEAM',
    DELETE_TEAM: 'DELETE_TEAM',
    ADDING_TEAM: 'ADDING_TEAM',
    ADD_TEAM_SUCCESS: 'ADD_TEAM_SUCCESS',
    ADD_TEAM_ERROR: 'ADD_TEAM_ERROR',
    RESET_TEAM: 'RESET_TEAM' 
}
export const teamsConstant = {
    GETTING_TEAMS_LIST: 'GETTING_TEAMS_LIST',
    GET_TEAMS_LIST_SUCCESS: 'GET_TEAMS_LIST_SUCCESS',
    GET_TEAMS_LIST_ERROR: 'GET_TEAMS_LIST_ERROR',

    DELTETING_TEAM: 'DELTETING_TEAMS',
    DELETE_TEAM_SUCCESS: 'DELETE_TEAM_SUCCESS',
    DELETE_TEAM_ERROR: 'DELETE_TEAM_ERROR',

    EDITING_TEAM: 'EDITING_TEAM',
    EDIT_TEAM_SUCCESS: 'EDIT_TEAM_SUCCESS',
    EDIT_TEAM_ERROR: 'EDIT_TEAM_ERROR',

    SET_SELECTED_TEAM: 'SET_SELECTED_TEAM',
    SET_IS_TEAM_MEMBER_ADDED: 'SET_IS_TEAM_MEMBER_ADDED',

    GETTING_TEAM_MEMBERS: 'GETTING_TEAM_MEMBERS',
    GET_TEAM_MEMBERS_SUCCESS: 'GET_TEAM_MEMBERS_SUCCESS',
    GET_TEAM_MEMBERS_ERROR: 'GET_TEAM_MEMBERS_ERROR',

    ADDING_TEAM_MEMBERS: 'ADDING_TEAM_MEMBERS',
    ADD_TEAM_MEMBERS_SUCCESS: 'ADD_TEAM_MEMBERS_SUCCESS',
    ADD_TEAM_MEMBERS_ERROR: 'ADD_TEAM_MEMBERS_ERROR',

    DELETING_TEAM_MEMBERS: 'DELETING_TEAM_MEMBERS',
    DELETE_TEAM_MEMBERS_SUCCESS: 'DELETE_TEAM_MEMBERS_SUCCESS',
    DELETE_TEAM_MEMBERS_ERROR: 'DELETE_TEAM_MEMBERS_ERROR',

    GETTING_ALL_ORG_USERS: 'GETTING_ALL_ORG_USERS',
    GET_ALL_ORG_USERS_SUCCESS: 'GET_ALL_ORG_USERS_SUCCESS',
    GET_ALL_ORG_USERS_ERROR: 'GET_ALL_ORG_USERS_ERROR',
}

export const rampTimeData = {
    GETTING_OPPORTUNITY_AMOUNT: 'GETTING_OPPORTUNITY_AMOUNT',
    GET_OPPORTUNITY_AMOUNT_SUCCESS: 'GET_OPPORTUNITY_AMOUNT_SUCCESS',
    GET_OPPORTUNITY_AMOUNT_FAIL: 'GET_OPPORTUNITY_AMOUNT_FAIL',

    GETTING_QUOTA_ATTAINMENT: 'GETTING_QUOTA_ATTAINMENT',
    GET_QUOTA_ATTAINMENT_SUCCESS: 'GET_QUOTA_ATTAINMENT_SUCCESS',
    GET_QUOTA_ATTAINMENT_FAIL: 'GET_QUOTA_ATTAINMENT_FAIL',
}

export const contentPortalConstant = {
    ADDING_GDRIVE_CONTENT: 'ADDING_GDRIVE_CONTENT',
    ADD_GDRIVE_CONTENT_SUCCESS: 'ADD_GDRIVE_CONTENT_SUCCESS',
    ADD_GDRIVE_CONTENT_ERROR: 'ADD_GDRIVE_CONTENT_ERROR',

    GETTING_GDRIVE_CONTENT: 'GETTING_GDRIVE_CONTENT',
    GET_GDRIVE_CONTENT_SUCCESS: 'GET_GDRIVE_CONTENT_SUCCESS',
    GET_GDRIVE_CONTENT_ERROR: 'GET_GDRIVE_CONTENT_ERROR',

    GETTING_CONTENT_TAG: 'GETTING_CONTENT_TAG',
    GET_CONTENT_TAG_SUCCESS: 'GET_CONTENT_TAG_SUCCESS',
    GET_CONTENT_TAG_ERROR: 'GET_CONTENT_TAG_ERROR',

    ADDING_TAGS_TO_CONTENTS: 'ADDING_TAGS_TO_CONTENTS',
    ADD_TAGS_TO_CONTENTS_SUCCESS: 'ADD_TAGS_TO_CONTENTS_SUCCESS',
    ADD_TAGS_TO_CONTENTS_ERROR: 'ADD_TAGS_TO_CONTENTS_ERROR',

    ADDING_CONTENTS_TO_PORTAL: 'ADDING_CONTENTS_TO_PORTAL',
    ADD_CONTENTS_TO_PORTAL_SUCCESS: 'ADD_CONTENTS_TO_PORTAL_SUCCESS',
    ADD_CONTENTS_TO_PORTAL_ERROR: 'ADD_CONTENTS_TO_PORTAL_ERROR',

    DELETING_CONTENTS: 'DELETING_CONTENTS',
    DELETE_CONTENTS_SUCCESS: 'DELETE_CONTENTS_SUCCESS',
    DELETE_CONTENTS_ERROR: 'DELETE_CONTENTS_ERROR',

    EDITING_PORTAL_CONTENT: 'EDITING_PORTAL_CONTENT',
    EDIT_PORTAL_CONTENT_SUCCESS: 'EDIT_PORTAL_CONTENT_SUCCESS',
    EDIT_PORTAL_CONTENT_ERROR: 'EDIT_PORTAL_CONTENT_ERROR',

    ADDING_MY_CONTENT: 'ADDING_MY_CONTENT',
    ADD_MY_CONTENT_SUCCESS: 'ADD_MY_CONTENT_SUCCESS',
    ADD_MY_CONTENT_ERROR: 'ADD_MY_CONTENT_ERROR',

    GETTING_MY_CONTENT: 'GETTING_MY_CONTENT',
    GET_MY_CONTENT_SUCCESS: 'GET_MY_CONTENT_SUCCESS',
    GET_MY_CONTENT_ERROR: 'GET_MY_CONTENT_ERROR',

    SET_SELECTED_MICROSITE_CONTENTS: 'SET_SELECTED_MICROSITE_CONTENTS',
    RESET_SELECTED_MICROSITE_CONTENTS: 'RESET_SELECTED_MICROSITE_CONTENTS',

    GETTING_LIBRARY_IMAGES: 'GETTING_LIBRARY_IMAGES',
    GET_LIBRARY_IMAGES_SUCCESS: 'GET_LIBRARY_IMAGES_SUCCESS',
    GET_LIBRARY_IMAGES_ERROR: 'GET_LIBRARY_IMAGES_ERROR',

    GETTING_POPULAR_CONTENT: 'GETTING_POPULAR_CONTENT',
    GET_POPULAR_CONTENT_SUCCESS: 'GET_POPULAR_CONTENT_SUCCESS',
    GET_POPULAR_CONTENT_ERROR: 'GET_POPULAR_CONTENT_ERROR',

    GETTING_RECOMMENDED_CONTENT: 'GETTING_RECOMMENDED_CONTENT',
    GET_RECOMMENDED_CONTENT_SUCCESS: 'GET_RECOMMENDED_CONTENT_SUCCESS',
    GET_RECOMMENDED_CONTENT_ERROR: 'GET_RECOMMENDED_CONTENT_ERROR',

    SENDING_RECOMMENDED_CONTENT: 'SENDING_RECOMMENDED_CONTENT',
    SEND_RECOMMENDED_CONTENT_SUCCESS: 'SEND_RECOMMENDED_CONTENT_SUCCESS',
    SEND_RECOMMENDED_CONTENT_ERROR: 'SEND_RECOMMENDED_CONTENT_ERROR',
    RESET_RECOMMENDED_CONTENT_ERROR: 'RESET_RECOMMENDED_CONTENT_ERROR',

    SAVE_SRCH_CONTENT_TAG: "SAVE_SRCH_CONTENT_TAG",
    SAVE_SRCH_WHEN_TO_SHARE: "SAVE_SRCH_WHEN_TO_SHARE",
    SAVE_SRCH_DATE_MODIFIED: "SAVE_SRCH_DATE_MODIFIED",
    HANDLE_FILTER_SRCH: "HANDLE_FILTER_SRCH",
    HANDLE_GLB_CONTENT_SRCH: "HANDLE_GLB_CONTENT_SRCH",
    RESET_SRCH_FILTER: "RESET_SRCH_FILTER",
    RESET_GLB_CONTENT_SRCH: "RESET_GLB_CONTENT_SRCH",

    GETTING_CONTENT_ANALYTICS: 'GETTING_CONTENT_ANALYTICS',
    GET_CONTENT_ANALYTICS_SUCCESS: 'GET_CONTENT_ANALYTICS_SUCCESS',
    GET_CONTENT_ANALYTICS_ERROR: 'GET_CONTENT_ANALYTICS_ERROR',
}

export const companyLogoConstant = {
    ADDING_COMPANY_LOGO: 'ADDING_COMPANY_LOGO',
    ADD_COMPANY_LOGO_SUCCESS: 'ADD_COMPANY_LOGO_SUCCESS',
    ADD_COMPANY_LOGO_ERROR: 'ADD_COMPANY_LOGO_ERROR',

    GETTING_COMPANY_LOGO: 'GETTING_COMPANY_LOGO',
    GET_COMPANY_LOGO_SUCCESS: 'GET_COMPANY_LOGO_SUCCESS',
    GET_COMPANY_LOGO_ERROR: 'GET_COMPANY_LOGO_ERROR',
}

export const micrositesConstant = {
    CREATING_MICROSITE: 'CREATING_MICROSITE',
    CREATE_MICROSITE_SUCCESS: 'CREATE_MICROSITE_SUCCESS',
    CREATE_MICROSITE_ERROR: 'CREATE_MICROSITE_ERROR',

    GETTING_MICROSITE_BY_LINK: 'GETTING_MICROSITE_BY_LINK',
    GET_MICROSITE_BY_LINK_SUCCESS: 'GET_MICROSITE_BY_LINK_SUCCESS',
    GET_MICROSITE_BY_LINK_ERROR: 'GET_MICROSITE_BY_LINK_ERROR',

    GETTING_MICROSITES: 'GETTING_MICROSITES',
    GET_MICROSITES_SUCCESS: 'GET_MICROSITES_SUCCESS',
    GET_MICROSITES_ERROR: 'GET_MICROSITES_ERROR',

    UPDATING_MICROSITE: 'CREATING_MICROSITE',
    UPDATE_MICROSITE_SUCCESS: 'UPDATE_MICROSITE_SUCCESS',
    UPDATE_MICROSITE_ERROR: 'UPDATE_MICROSITE_ERROR',

    SAVING_GET_SHARE_LINK: 'SAVING_GET_SHARE_LINK',
    SAVE_GET_SHARE_LINK_SUCCESS: 'SAVE_GET_SHARE_LINK_SUCCESS',
    SAVE_GET_SHARE_LINK_ERROR: 'SAVE_GET_SHARE_LINK_ERROR',

    SAVING_UPLOAD_VIDEO_DATA: 'SAVING_UPLOAD_VIDEO_DATA',
    SAVE_UPLOAD_VIDEO_DATA_SUCCESS: 'SAVE_UPLOAD_VIDEO_DATA_SUCCESS',
    SAVE_UPLOAD_VIDEO_DATA_ERROR: 'SAVE_UPLOAD_VIDEO_DATA_ERROR',

    UPLOADING_MICROSITE_RECORDED_VIDEO: 'UPLOADING_MICROSITE_RECORDED_VIDEO',
    UPLOAD_MICROSITE_RECORDED_VIDEO_SUCCESS: 'UPLOAD_MICROSITE_RECORDED_VIDEO_SUCCESS',
    UPLOAD_MICROSITE_RECORDED_VIDEO_FAIL: 'UPLOAD_MICROSITE_RECORDED_VIDEO_FAIL',

    SAVING_CTA_TEXT_DATA: 'SAVING_CTA_TEXT_DATA',
    SAVE_CTA_TEXT_DATA_SUCCESS: 'SAVE_CTA_TEXT_DATA_SUCCESS',
    SAVE_CTA_TEXT_DATA_ERROR: 'SAVE_CTA_TEXT_DATA_ERROR',

    GETTING_MY_SHARES: 'GETTING_MY_SHARES',
    GET_MY_SHARES_SUCCESS: 'GET_MY_SHARES_SUCCESS',
    GET_MY_SHARES_ERROR: 'GET_MY_SHARES_ERROR',

    DELETING_MICROSITE_CONTENTS: 'DELETING_MICROSITE_CONTENTS',
    DELETE_MICROSITE_CONTENTS_SUCCESS: 'DELETE_MICROSITE_CONTENTS_SUCCESS',
    DELETE_MICROSITE_CONTENTS_ERROR: 'DELETE_MICROSITE_CONTENTS_ERROR',

    ADDING_CONTENT_TO_MICROSITE: 'ADDING_CONTENT_TO_MICROSITE',
    ADD_CONTENT_TO_MICROSITE_SUCCESS: 'ADD_CONTENT_TO_MICROSITE_SUCCESS',
    ADD_CONTENT_TO_MICROSITE_ERROR: 'ADD_CONTENT_TO_MICROSITE_ERROR',
    RESET_ADD_CONTENT_TO_MICROSITE_ERROR: 'RESET_ADD_CONTENT_TO_MICROSITE_ERROR',
}

export const experiencesConstant = {
    CREATING_EXPERIENCE: 'CREATING_EXPERIENCE',
    CREATE_EXPERIENCE_SUCCESS: 'CREATE_EXPERIENCE_SUCCESS',
    CREATE_EXPERIENCE_ERROR: 'CREATE_EXPERIENCE_ERROR',

    GETTING_EXPERIENCES: 'GETTING_EXPERIENCES',
    GET_EXPERIENCES_SUCCESS: 'GET_EXPERIENCES_SUCCESS',
    GET_EXPERIENCES_ERROR: 'GET_EXPERIENCES_ERROR',

    GETTING_EXPERIENCE_BY_LINK: 'GETTING_EXPERIENCE_BY_LINK',
    GET_EXPERIENCE_BY_LINK_SUCCESS: 'GET_EXPERIENCE_BY_LINK_SUCCESS',
    GET_EXPERIENCE_BY_LINK_ERROR: 'GET_EXPERIENCE_BY_LINK_ERROR',

    UPDATING_EXPERIENCE: 'UPDATING_EXPERIENCE',
    UPDATE_EXPERIENCE_SUCCESS: 'UPDATE_EXPERIENCE_SUCCESS',
    UPDATE_EXPERIENCE_ERROR: 'UPDATE_EXPERIENCE_ERROR',

    RESET_EXP_BY_LINK_DATA: 'RESET_EXP_BY_LINK_DATA',

    GETTING_DEF_EXP_TEMPLATES: 'GETTING_DEF_EXP_TEMPLATES',
    GET_DEF_EXP_TEMPLATES_SUCCESS: 'GET_DEF_EXP_TEMPLATES_SUCCESS',
    GET_DEF_EXP_TEMPLATES_ERROR: 'GET_DEF_EXP_TEMPLATES_ERROR',

    GETTING_DEF_EXP_TEMPLATES_BY_LINK: 'GETTING_DEF_EXP_TEMPLATES_BY_LINK',
    GET_DEF_EXP_TEMPLATES_BY_LINK_SUCCESS: 'GET_DEF_EXP_TEMPLATES_BY_LINK_SUCCESS',
    GET_DEF_EXP_TEMPLATES_BY_LINK_ERROR: 'GET_DEF_EXP_TEMPLATES_BY_LINK_ERROR',
    RESET_DEF_EXP_TEMPLATES_BY_LINK: 'RESET_DEF_EXP_TEMPLATES_BY_LINK',
}